-- MySQL Script generated by MySQL Workbench
-- Mon 25 Apr 2016 10:02:07 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema filterfox
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema filterfox
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `filterfox` DEFAULT CHARACTER SET utf8 ;
USE `filterfox` ;

-- -----------------------------------------------------
-- Table `filterfox`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filterfox`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `bio` TEXT NULL COMMENT '',
  `photo` VARCHAR(450) NULL COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filterfox`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filterfox`.`post` (
  `post_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `post_date` DATETIME NOT NULL COMMENT '',
  `post_content` VARCHAR(400) NOT NULL COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `likes` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`post_id`)  COMMENT '',
  INDEX `p_user_Id_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Customer_Id`
    FOREIGN KEY (`user_id`)
    REFERENCES `filterfox`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filterfox`.`post_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filterfox`.`post_comment` (
  `comment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `post_id` INT UNSIGNED NOT NULL COMMENT '',
  `comment_content` VARCHAR(400) NOT NULL COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `date` DATETIME NULL COMMENT '',
  PRIMARY KEY (`comment_id`)  COMMENT '',
  INDEX `fk_Order_Id_idx` (`post_id` ASC)  COMMENT '',
  INDEX `fk_user_id_post` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `filterfox`.`post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `filterfox`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filterfox`.`user_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filterfox`.`user_access` (
  `user_id` INT UNSIGNED NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(18) NULL COMMENT '',
  PRIMARY KEY (`email`)  COMMENT '',
  CONSTRAINT `fk_user_id_a`
    FOREIGN KEY (`user_id`)
    REFERENCES `filterfox`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filterfox`.`post_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filterfox`.`post_like` (
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `post_id` INT UNSIGNED NOT NULL COMMENT '',
  INDEX `likes_post_id_idx` (`post_id` ASC)  COMMENT '',
  INDEX `likes_user_idx` (`user_id` ASC)  COMMENT '',
  PRIMARY KEY (`user_id`, `post_id`)  COMMENT '',
  CONSTRAINT `likes_post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `filterfox`.`post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `likes_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `filterfox`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filterfox`.`post_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filterfox`.`post_view` (
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `post_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`user_id`, `post_id`)  COMMENT '',
  INDEX `view_post_id_idx` (`post_id` ASC)  COMMENT '',
  CONSTRAINT `view_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `filterfox`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `view_post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `filterfox`.`post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
